version: '3.8'
services:
  nest-api-1:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3000"
    depends_on:
      - postgres
      - minio
      - redis
    env_file:
      - ../.env

  nest-api-2:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3001"
    depends_on:
      - postgres
      - minio
      - redis
    env_file:
      - ../.env

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nest-api-1
      - nest-api-2

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres:
    name: nest-prisma-docker-db
  minio-storage:
